### ISSUE TITLE
Kanban Board Setup Review

### ISSUE THREAD

**Issue by geekelo** [geekelo/personal-inventory#39]
Link to Project Kanban Board - https://github.com/geekelo/personal-inventory/projects/1
Team Number - Four(4) team members
Team member 1 @melkamu12 
Team member 2 @Paulinelali 
Team member 3 @Chandan-devs-tech 
Team member 4 @geekelo

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)


# Hi @geekelo, @melkamu12, @Chandan-devs-tech & @Paulinelali  👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Correct Kanban template is used ✔
- Proper information about team members ✔
- Each card is assigned a team member ✔

## Required Changes ♻️
- Pelase make sure to provide a proper description for each task as I noticed some cards with no description as shown below 
  ![firefox_RJHlo7kDMa](https://github.com/geekelo/personal-inventory/assets/104968236/cb0fa2dc-8544-4b34-bad2-f3b86d29b54a)
- Also make sure all requirements from the list for a given student in the [project requirements divided by team member ](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) file have a corresponding card in the Kanban board. for example, I noticed team member 1 doesn't have a card for listing the menu options (all books, all labels & add a book).
  - This applies to all members who don't have a corresponding card from the project requirements so please carefully revise them.
- Please make sure each card is assigned a valid point in the [Xpt] prefix for example I noticed team member 2 has a card with no points as shown below:
  ![image](https://github.com/geekelo/personal-inventory/assets/104968236/83209baa-5a87-4049-b29e-4a9d19dca7ce)
- Kindly make sure each card is distributed fairly as I noticed some members have cards with higher points assigned and others have lesser points. As a note make sure the difference between each member's total points is not larger than 5 points  (difference should be <= 5 points).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
